# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Lorem ipsum"  # 👈 建议修改为："Zhang Lei Group Homepage"
description              : "Lorem ipsum dolor sit amet..." # 👈 建议修改为一句话课题组简介，比如："Research group at NENU focusing on Image Restoration and Computer Vision."
repository               : "RayeRen/acad-homepage.github.io" # 👈 建议修改为："ZhangLeiGroup/ZhangLeiGroup.github.io"# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name: "Lei Zhang(张蕾)"
  avatar: "/images/avatar.jpg" # 这里填入头像照片的路径，如果没有照片可以把这行删掉或注释掉
  bio: "Senior Engineer (Associate Senior Level)<br>School of Physics, Northeast Normal University" # 使用 <br> 来强制换行，保持和图片一样的排版
  location: "Changchun, China" # 可以选填，不需要的话直接整行删除
  email: "zhangl179@nenu.edu.cn"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zhangl179@nenu.edu.cn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ZhangLeiGroup" # 这里我默认填了你课题组的GitHub主页，如果有导师个人的可以替换
    - label: "WeChat"
      icon: "fab fa-fw fa-weixin"
      url: "你的微信号或者微信二维码图片链接" # 微信通常没有直接打开的网页链接，你可以填上微信号或者改为跳转到二维码图片的链接


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
